@startuml

interface ISource{
    + Function1S() : void
    + Function2S() : void 
}

interface ITarget{
    + Function1T() : void
    + Function2T() : void
}

class Target{
    - soruce : ISource

    + Function1T() : void
    + Function2T() : void
}

class Source{
    + Function1S() : void
    + Function2S() : void 
}


'Relations

Target --|> ITarget
Source --|> ISource

Target --> Source

@enduml