@startuml

interface IItem {
    + operation() : void
}

class LeafItem {
    + operation() : void
}

class CompositeItem {
    - children : List<IItem>
    + add(item : IItem) : void
    + remove(item : IItem) : void
    + operation() : void
}

IItem <|.. LeafItem
IItem <|.. CompositeItem

' 
CompositeItem "1" o-- "0..*" IItem : contains //Aggregation relationship 

@enduml