@startuml

'Interface
interface IProductA
{

}

interface IProductB
{

}

interface IFactory
{
    createProductA() : IProductA
    createProductB() : IProductB
}


'Products
class ProductA1
{

}

class ProductA2
{

}

class ProductB1
{

}

class ProductB2
{

}

class Factory1
{

}

class Factory2
{

}


ProductA1 ..|> IProductA
ProductA2 ..|> IProductA

ProductB1 ..|> IProductB
ProductB2 ..|> IProductB

IFactory --|> IProductA
IFactory --|> IProductB

Factory1 ..|> IFactory
Factory2 ..|> IFactory

@enduml