class Product {
    - id : int
    - name : String
    - price : int
}

class "Product.Builder" as Builder <<static>> {
    - id : int
    - name : String
    - price : int

    + id(id : int) : Builder
    + name(name : String) : Builder
    + price(price : int) : Builder
    + build() : Product
}

Product +-- Builder