@startuml


interface IProduct
{
  
}


interface IFactory
{
  + createNewProduct() : IProduct
}

class FactoryA
{
  + createNewProduct() : ProductA
}

class ProductA
{

}

class Client
{

}


ProductA --|> IProduct
FactoryA --|> IFactory

IFactory --> IProduct : Uses

FactoryA --> ProductA : Uses

Client --> FactoryA : has

@enduml