@startuml

'Interfaces
interface IObserver
{
    + notify(Message : String);
}

interface ISubject
{
    + addObserver() : void()
    + removeObserver() : void()
    + notifyObserver() : void()
}

'Classes

class Observer
{
    +notify(Message : String)
}

class Subject
{
    - observers : List<IObserver>

    + addObserver() : void()
    + removeObserver() : void()
    + notifyObserver() : void()

}

'Relations
Observer ..|> IObserver
Subject ..|> ISubject
ISubject --|> IObserver 


@enduml