@startuml

interface IStratergy
{
  + performAction()
}

class Stratergy1 
{
  + performAction()
}

class Stratergy2
{
  + performAction()
}

class Stratergy3
{
 + performAction()
}

Stratergy1 --|> IStratergy

Stratergy2 --|> IStratergy

Stratergy3 --|> IStratergy

Context --> IStratergy : has

Client --> Stratergy1 : uses
Client --> Stratergy2 : uses
Client --> Stratergy3 : uses
Client --> Context : has
class Context
{
  - stratergy : IStratergy 
  
  + Client(IStratergy stratergy)
  + setStratergy(IStratergy stratergy): void
  + performAction()
}

class Client
{
  - context : Context
  
  
}




@enduml
